### PR TITLE
preprocessed and tested data with 4 models

### PR DESCRIPTION
**Pull request by FiyinfobaO**
Nan values was handled, outliers were removed from 'price' and 'odometers' columns, the categorical values were converted to numbers and 4 different models was trained on the data using Linear Regression, Decision Trees, Random Forest and Extra Trees Regressor models.

[Here](https://github.com/FiyinfobaO/g05-used-cars/blob/master/demo_model.ipynb) is the link to the notebook.

### CODE REVIEW

**Comment by FiyinfobaO** [comment]
4 more models were added: LGBM, catboost, XGB and XGBRF Regressor models. 
The Extra Trees Regressor gave the highest R2 score of 0.922 and the lowest mae of 1546.146.

[Here](https://github.com/FiyinfobaO/g05-used-cars/blob/master/demo_model.ipynb) is the link to the notebook

**Comment by olufunmiruth** [comment]
This looks good.

**Comment by mickynnamdi** [comment]
Impressive work. I noticed you removed the year column, i guess it because of the age column you derived.

**Comment by FiyinfobaO** [comment]
> This looks good.

Thanks

**Comment by FiyinfobaO** [comment]
> Impressive work. I noticed you removed the year column, i guess it because of the age column you derived.

Thanks.
Yeah that was why it was removed

**Comment by FiyinfobaO** [comment]
Grid search was used to get better parameters to use when training both the catboost and the Extra Trees Regressor models. A better R2 score was gotten in the catboost of 0.908 while the Extra Trees gave the same R2 score of 0.922 with a better mae, mse and rmse value.

[Here](https://github.com/FiyinfobaO/g05-used-cars/blob/master/demo_model.ipynb) is the link to the notebook.

**Comment by sophiabj** [comment]
Nice work!

**Comment by FiyinfobaO** [comment]
From the preprocessed data, outliers were removed from 'price' and 'odometers' columns, the categorical values were converted to numbers and 8 different models was trained on the data using Linear Regression, Decision Trees, Random Forest, Extra Trees Regressor, LGBM, catboost, XGB and XGBRF Regressor models

From all the models used, ExtraTrees Regressor gave the highest R2 score of 0.928 with the lowest mae value of 1489.648

[Here](https://github.com/FiyinfobaO/g05-used-cars/blob/master/Preprocessing_and_modelling.ipynb) is the link to the notebook.

**Pull request merged**
