### PR TITLE
Data Preprocessing - Exploratory Data Analysis and filling NaN Values

### PR DESCRIPTION
**Pull request by EkeminiUmanah**
Data Preprocessing - Exploratory Data Analysis and filling NaN Values

### CODE REVIEW

**Comment by olufunmiruth** [comment]
I find your method of filling the nan values quite interesting.

**Comment by mickynnamdi** [comment]
This is an impressive approach, have you considered it performance during model building

**Comment by EkeminiUmanah** [comment]
> I find your method of filling the nan values quite interesting.

**Comment by EkeminiUmanah** [comment]
> This is an impressive approach, have you considered it performance during model building

@mickynnamdi, Thanks. Yes, I'll test the model on both this dataset and one where the NaNs were dropped, see which performs better

**Pull request merged**
